---
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    checks:
      wrap-iife:
        enabled: false
      no-loop-func:
        enabled: false       
      guard-for-in:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths: []
